spring:
  application:
    name: dnf-master
  aop:
    auto: true
    proxy-target-class: true


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

concurrent:
  max-pool-size: 2
  core-pool-size: 1
  thread-name-prefix: async-task-thread-